### ISSUE TITLE
Comenta brevemente la razón de buscar la correlación y/o los resultados

### ISSUE THREAD

**Issue by JJ** [OpenScienceGames/Games#10]
Muchos gráficos, poco análisis, no es la mejor forma de presentar información. @marcelinocabrera mira los gráficos (y el análisis que representan) y tratad de sacar con @TorresM alguna conclusión.

**Comment by marcelinocabrera** [comment]
Introducida una justificación del análisis de los datos en la introducción y como se observa de los datos no se pueden sacar conclusiones importantes relacionadas con la hipótesis de partida
