### ISSUE TITLE
Limpia el repo de binarios

### ISSUE THREAD

**Issue by JJ** [OpenScienceGames/Games#6]
Algunos binarios como hojas Excel no corresponden en el repo; deben estar sólo ficheros de texto. @marcelinocabrera por favor, encárgate.

**Comment by marcelinocabrera** [comment]
Hecho.

Eliminados binarios y archivos innecesarios

**Comment by JJ** [comment]
Directamente desde el commit puedes hacer "closes #xxx" para cerrar el
issue.
